openapi: 3.2.0
info:
  title: Blue Prism Subscriptions API
  description: An API to expose core functionality of the Blue Prism product.
  version: 7.5.1
security:
- Bearer:
  - bp-api
  - bpserver
- OAuth2:
  - bp-api
  - bpserver
tags:
- name: Subscriptions
paths:
  /api/v7/subscriptions/{subscriptionId}:
    patch:
      summary: Update the subscription for the given subscription ID
      operationId: updatesubscription
      description: '> ### Permissions required

        At least one of: `Full Access to webhooks`'
      tags:
      - Subscriptions
      parameters:
      - name: subscriptionId
        in: path
        description: The ID of the subscription to update.
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchRequest'
              examples: null
              replace:
                $ref: '#/components/examples/PatchReplaceExample'
      responses:
        '202':
          description: The session has been successfully updated.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    PatchDocument:
      description: A JSONPatch document as defined by RFC 6902. See http://jsonpatch.com/
      required:
      - op
      - path
      properties:
        op:
          type: string
          description: The operation to be performed.
          enum:
          - add
          - remove
          - replace
          - move
          - copy
        path:
          type: string
          description: A JSON-Pointer.
        value:
          type: object
          description: The value to be used within the operations..
        from:
          type: string
          description: A string containing a JSON Pointer value.
    ErrorMessage:
      description: A message describing the problem encountered.
      type: string
    UrlParameterError:
      description: An error occurred due to incorrect data supplied to url parameter.
      type: object
      properties:
        message:
          type: string
          description: A message about the error.
        messageDetail:
          type: string
          description: A detailed description about the error.
    PatchRequest:
      description: A request containing a JSON Patch document. See PatchDocument for details.
      type: array
      items:
        $ref: '#/components/schemas/PatchDocument'
    ValidationError:
      description: An error occurred during validation. See the response body for details on the invalid field.
      type: object
      properties:
        invalidField:
          type: string
          description: The field which is invalid.
        message:
          type: string
          description: A description of the error found with the field.
  responses:
    Forbidden:
      description: The authentication token does not give sufficient permissions to perform this action.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    NotAuthorized:
      description: The authentication token was either missing or invalid and must be refreshed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    NotFound:
      description: The requested resource could not be found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    BadRequest:
      description: The request is malformed or contains incorrect information. See the response for more details.
      content:
        application/json:
          schema:
            oneOf:
            - $ref: '#/components/schemas/UrlParameterError'
            - $ref: '#/components/schemas/ValidationError'
  examples:
    PatchReplaceExample:
      summary: Replace the value in a property.
      value:
      - op: replace
        path: /property
        value: propertyValue
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: JWT token issued from Authentication Server.
      bearerFormat: JWT
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth-server/connect/token
          scopes:
            bp-api: API scope
            bpserver: Blue Prism Application scope
